-- Add configurable member-priority non-member holds and refresh untouched starter policy copy.
ALTER TABLE "BookingDefaults" ADD COLUMN "nonMemberHoldEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BookingPeriod" ADD COLUMN "nonMemberHoldEnabled" BOOLEAN NOT NULL DEFAULT true;

UPDATE "PageContent"
SET "contentHtml" = $cms$<div class="website-legal-copy">
<div><h2>1. Agreement to Terms</h2><p>By registering an account or using the {{club-name}} Incorporated (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) booking and membership system (&ldquo;the System&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the System.</p><p>These terms apply to all users of the System, including club members, non-member guests, and any other visitors.</p></div>
<div><h2>2. Eligibility</h2><ul><li>You must be 18 years or older to create an account.</li><li>Children and youth members must be managed by a parent or guardian who holds an account.</li><li>Membership is subject to approval by the {{club-name}} committee. Creating an account does not constitute membership.</li><li>You must provide accurate and truthful information when registering. False information may result in account suspension.</li></ul></div>
<div><h2>3. Booking Rules</h2><ul><li>Lodge bookings are for accommodation at Waldvogel Lodge, Iwikau Village, Mt Ruapehu. The lodge sleeps a maximum of {{lodge-capacity}} guests.</li><li>Bookings must be made through the System. Verbal or informal bookings are not accepted.</li><li>Members may book for themselves and invite non-member guests. The booking member must be present during the stay of any non-member guests.</li><li>The committee configures whether bookings with non-member guests use Members First priority holds or First Paid, First In payment. See Section 5 for details.</li><li>All guests must participate in the lodge chore roster. Chore assignments are allocated by the hut leader for each night.</li><li>Guests must treat the lodge, equipment, and other guests with respect. The committee reserves the right to refuse future bookings to guests who cause damage or behave inappropriately.</li><li>The lodge is a shared facility. Quiet hours are from 10pm to 7am. Alcohol consumption must be responsible and is not permitted in common areas after quiet hours.</li></ul></div>
<div><h2>4. Payment Terms</h2><ul><li>Lodge accommodation fees are charged per person per night based on age group and membership status. Current rates are published on the <a href="/join">Join page</a>.</li><li>For confirmed bookings and First Paid, First In bookings, payment is collected immediately via Stripe at the time of booking.</li><li>When Members First priority holds apply, a payment method is saved for the pending non-member portion and is not charged until the booking is confirmed inside the configured threshold before check-in.</li><li>Annual membership subscriptions are invoiced separately through Xero and must be current to access member booking rates.</li><li>All prices are in {{currency}} inclusive of GST where applicable.</li><li>Payment processing is handled by Stripe. {{club-name}} does not store credit card details.</li></ul></div>
<div><h2>5. Non-Member Booking Priority</h2><p>The committee can choose the booking policy for stays that include non-member guests:</p><ul><li><strong>Members First:</strong> non-member guests outside the configured confirmation threshold are held as &ldquo;Pending&rdquo;. If a member booking requires that capacity before the hold is confirmed, pending non-member bookings may be cancelled (&ldquo;bumped&rdquo;) until sufficient capacity is available.</li><li><strong>First Paid, First In:</strong> non-member guests are included in the normal booking and payment flow immediately, with no provisional member-priority hold.</li><li>Bumped bookings receive a full refund and immediate email notification.</li><li>{{club-name}} accepts no liability for costs incurred by guests (e.g. travel, equipment hire) as a result of a booking being bumped.</li></ul></div>
<div><h2>6. Cancellation and Refunds</h2><p>Refunds are calculated based on the cancellation policy set by the {{club-name}} committee. Current tiers are shown on the <a href="/rules">Club Rules</a> page. General principles:</p><ul><li>Cancellations with 14 or more days' notice: full refund.</li><li>Cancellations with 7 to 13 days' notice: partial refund (as per current policy).</li><li>Cancellations with less than 7 days' notice: no refund.</li><li>A change fee may apply to date modifications made within the late-notice period.</li><li>Refunds are processed to the original payment method within 5&ndash;10 business days.</li><li>{{club-name}} reserves the right to cancel a booking due to circumstances beyond our control (e.g. natural disaster, lodge damage) and will provide a full refund in such cases.</li></ul></div>
<div><h2>7. Member Conduct</h2><ul><li>You are responsible for the conduct of all guests on your booking.</li><li>You must not make bookings on behalf of others without their knowledge and consent.</li><li>Any damage to lodge property caused by you or your guests may be invoiced to you.</li><li>Abuse of the booking system (e.g. making and cancelling bookings repeatedly to block dates) may result in account suspension.</li><li>New members must attend their first stay accompanied by their nominating members for lodge induction.</li></ul></div>
<div><h2>8. Account Security</h2><ul><li>You are responsible for keeping your account credentials confidential. Do not share your password with others.</li><li>If you suspect your account has been compromised, change your password immediately and contact us.</li><li>{{club-name}} accepts no liability for losses resulting from unauthorised access to your account due to your failure to maintain credential security.</li></ul></div>
<div><h2>9. Limitation of Liability</h2><p>The {{club-name}} is a volunteer-run, not-for-profit organisation. To the maximum extent permitted by New Zealand law:</p><ul><li>The System is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied.</li><li>{{club-name}} is not liable for any indirect, incidental, or consequential losses arising from use of the System or the lodge.</li><li>{{club-name}} is not responsible for personal injury, loss of property, or other incidents occurring during your lodge stay. All guests are advised to hold appropriate personal insurance.</li><li>Nothing in these terms excludes any rights you may have under the Consumer Guarantees Act 1993 or the Fair Trading Act 1986.</li></ul></div>
<div><h2>10. Account Suspension and Termination</h2><ul><li>{{club-name}} may suspend or terminate an account for breach of these terms, unpaid membership fees, or conduct that is harmful to the club or other members.</li><li>You may request deletion of your account from your Profile page. Deletion will cancel any future bookings (with refunds per the cancellation policy) and anonymise your personal data. Financial records required by law are retained.</li><li>Admin accounts cannot be deleted by the account holder &mdash; contact another administrator.</li></ul></div>
<div><h2>11. Changes to These Terms</h2><p>{{club-name}} may update these Terms of Service from time to time. We will update the &ldquo;Last updated&rdquo; date at the top of this page. Continued use of the System after any changes constitutes acceptance of the updated terms.</p></div>
<div><h2>12. Governing Law</h2><p>These terms are governed by the laws of New Zealand. Any disputes will be subject to the exclusive jurisdiction of the New Zealand courts.</p></div>
<div><h2>13. Contact Us</h2><p>For questions about these terms, please <a href="/contact">contact us</a>.</p></div>
</div>$cms$,
    "updatedAt" = NOW()
WHERE "slug" = 'terms'
  AND "contentHtml" = $previous$<div class="website-legal-copy">
<div><h2>1. Agreement to Terms</h2><p>By registering an account or using the {{club-name}} Incorporated (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) booking and membership system (&ldquo;the System&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the System.</p><p>These terms apply to all users of the System, including club members, non-member guests, and any other visitors.</p></div>
<div><h2>2. Eligibility</h2><ul><li>You must be 18 years or older to create an account.</li><li>Children and youth members must be managed by a parent or guardian who holds an account.</li><li>Membership is subject to approval by the {{club-name}} committee. Creating an account does not constitute membership.</li><li>You must provide accurate and truthful information when registering. False information may result in account suspension.</li></ul></div>
<div><h2>3. Booking Rules</h2><ul><li>Lodge bookings are for accommodation at Waldvogel Lodge, Iwikau Village, Mt Ruapehu. The lodge sleeps a maximum of {{lodge-capacity}} guests.</li><li>Bookings must be made through the System. Verbal or informal bookings are not accepted.</li><li>Members may book for themselves and invite non-member guests. The booking member must be present during the stay of any non-member guests.</li><li>Non-member bookings more than 7 days in advance are held as &ldquo;Pending&rdquo; and may be bumped if capacity is required for member bookings. See Section 5 for details.</li><li>All guests must participate in the lodge chore roster. Chore assignments are allocated by the hut leader for each night.</li><li>Guests must treat the lodge, equipment, and other guests with respect. The committee reserves the right to refuse future bookings to guests who cause damage or behave inappropriately.</li><li>The lodge is a shared facility. Quiet hours are from 10pm to 7am. Alcohol consumption must be responsible and is not permitted in common areas after quiet hours.</li></ul></div>
<div><h2>4. Payment Terms</h2><ul><li>Lodge accommodation fees are charged per person per night based on age group and membership status. Current rates are published on the <a href="/join">Join page</a>.</li><li>For confirmed bookings (members only, or bookings within 7 days of check-in), payment is collected immediately via Stripe at the time of booking.</li><li>For pending bookings (non-member guests, more than 7 days in advance), a payment method is saved but not charged until the booking is confirmed approximately 7 days before check-in.</li><li>Annual membership subscriptions are invoiced separately through Xero and must be current to access member booking rates.</li><li>All prices are in {{currency}} inclusive of GST where applicable.</li><li>Payment processing is handled by Stripe. {{club-name}} does not store credit card details.</li></ul></div>
<div><h2>5. Non-Member Priority System</h2><p>The {{club-name}} is a members' club. Members have priority access to the lodge. The following rules apply to bookings that include non-member guests:</p><ul><li>Bookings including non-members made more than 7 days before check-in are held as &ldquo;Pending&rdquo;.</li><li>If a member booking requires capacity that a pending non-member booking occupies, the most recently made pending bookings are cancelled (&ldquo;bumped&rdquo;) until sufficient capacity is available.</li><li>Bumped bookings receive a full refund and immediate email notification.</li><li>{{club-name}} accepts no liability for costs incurred by guests (e.g. travel, equipment hire) as a result of a booking being bumped.</li></ul></div>
<div><h2>6. Cancellation and Refunds</h2><p>Refunds are calculated based on the cancellation policy set by the {{club-name}} committee. Current tiers are shown on the <a href="/rules">Club Rules</a> page. General principles:</p><ul><li>Cancellations with 14 or more days' notice: full refund.</li><li>Cancellations with 7 to 13 days' notice: partial refund (as per current policy).</li><li>Cancellations with less than 7 days' notice: no refund.</li><li>A change fee may apply to date modifications made within the late-notice period.</li><li>Refunds are processed to the original payment method within 5&ndash;10 business days.</li><li>{{club-name}} reserves the right to cancel a booking due to circumstances beyond our control (e.g. natural disaster, lodge damage) and will provide a full refund in such cases.</li></ul></div>
<div><h2>7. Member Conduct</h2><ul><li>You are responsible for the conduct of all guests on your booking.</li><li>You must not make bookings on behalf of others without their knowledge and consent.</li><li>Any damage to lodge property caused by you or your guests may be invoiced to you.</li><li>Abuse of the booking system (e.g. making and cancelling bookings repeatedly to block dates) may result in account suspension.</li><li>New members must attend their first stay accompanied by their nominating members for lodge induction.</li></ul></div>
<div><h2>8. Account Security</h2><ul><li>You are responsible for keeping your account credentials confidential. Do not share your password with others.</li><li>If you suspect your account has been compromised, change your password immediately and contact us.</li><li>{{club-name}} accepts no liability for losses resulting from unauthorised access to your account due to your failure to maintain credential security.</li></ul></div>
<div><h2>9. Limitation of Liability</h2><p>The {{club-name}} is a volunteer-run, not-for-profit organisation. To the maximum extent permitted by New Zealand law:</p><ul><li>The System is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied.</li><li>{{club-name}} is not liable for any indirect, incidental, or consequential losses arising from use of the System or the lodge.</li><li>{{club-name}} is not responsible for personal injury, loss of property, or other incidents occurring during your lodge stay. All guests are advised to hold appropriate personal insurance.</li><li>Nothing in these terms excludes any rights you may have under the Consumer Guarantees Act 1993 or the Fair Trading Act 1986.</li></ul></div>
<div><h2>10. Account Suspension and Termination</h2><ul><li>{{club-name}} may suspend or terminate an account for breach of these terms, unpaid membership fees, or conduct that is harmful to the club or other members.</li><li>You may request deletion of your account from your Profile page. Deletion will cancel any future bookings (with refunds per the cancellation policy) and anonymise your personal data. Financial records required by law are retained.</li><li>Admin accounts cannot be deleted by the account holder &mdash; contact another administrator.</li></ul></div>
<div><h2>11. Changes to These Terms</h2><p>{{club-name}} may update these Terms of Service from time to time. We will update the &ldquo;Last updated&rdquo; date at the top of this page. Continued use of the System after any changes constitutes acceptance of the updated terms.</p></div>
<div><h2>12. Governing Law</h2><p>These terms are governed by the laws of New Zealand. Any disputes will be subject to the exclusive jurisdiction of the New Zealand courts.</p></div>
<div><h2>13. Contact Us</h2><p>For questions about these terms, please <a href="/contact">contact us</a>.</p></div>
</div>$previous$;

UPDATE "PageContent"
SET "contentHtml" = $cms$<div class="website-legal-copy">
<div><h2>Booking &amp; Stays</h2><details><summary>How do I book a stay at the lodge?</summary><p>Members can book directly through this website. Log in, click "Book a Stay", select your dates and add your guests. The calendar shows available beds for each night. You'll need a current membership subscription to book at member rates.</p></details><details><summary>What is the cancellation policy?</summary><p>Refunds are tiered based on how much notice you give. Generally, cancellations 14 or more days before your stay receive a full refund. Between 7 and 14 days you receive a partial refund, and cancellations with less than 7 days' notice receive no refund. The exact tiers are set by the committee and shown on the Club Rules page. Always cancel as early as possible if your plans change.</p></details><details><summary>What are the nightly rates?</summary><p>Rates vary by season (Winter and Summer) and by age group (Adult, Youth, Child). Members pay a significantly lower rate than non-member guests. Current rates are shown on the Join page. Non-member guests must be accompanied by a financial member.</p></details><details><summary>Can I stay at the lodge as a non-member?</summary><p>Yes, but you must be invited as a guest by a current financial member, who must also be staying at the lodge during your visit. Depending on the club's current Booking Policies, your booking may either be paid and confirmed immediately under First Paid, First In, or held under Members First until the configured non-member confirmation threshold.</p></details><details><summary>How does the non-member priority (bumping) system work?</summary><p>When Members First is enabled, the lodge gives priority to member bookings. Non-member guests booked outside the configured threshold are held as "Pending" until the hold expires. If a member needs those beds and the lodge is at capacity, pending non-member bookings may be bumped to free up space. You'll be notified immediately by email and receive a full refund. Under First Paid, First In, the provisional hold and bumping copy do not apply.</p></details><details><summary>Can I change my booking dates?</summary><p>Yes, members can change their booking dates from the booking detail page, subject to availability. A change fee may apply if you're modifying a booking within the late-notice period. The system will show you the fee before you confirm the change.</p></details></div>
<div><h2>Membership</h2><details><summary>How do I become a member?</summary><p>Membership is by nomination. You need to be nominated by two existing financial members. Start by visiting the lodge as someone's guest, get to know some members, and ask if they'd be willing to nominate you. See the Join page for the full process.</p></details><details><summary>What does membership cost?</summary><p>There is a one-off entrance fee for new members, plus an annual subscription. Subscriptions run April to March and are invoiced through Xero. Family memberships cover all household members at a reduced combined rate. Contact the Treasurer for current fee amounts.</p></details><details><summary>When does the membership year run?</summary><p>The membership year runs from 1 April to 31 March. Annual subscriptions are due at the start of each year. Members with unpaid subscriptions lose access to member booking rates until their subscription is paid.</p></details><details><summary>How do I reset my password?</summary><p>Click "Forgot password?" on the login page and enter your email address. You'll receive a password reset link valid for one hour. If you don't receive the email, check your spam folder or contact the Booking Officer.</p></details></div>
<div><h2>The Lodge</h2><details><summary>What facilities does the lodge have?</summary><p>Waldvogel Lodge at Iwikau Village, Mt Ruapehu sleeps up to {{lodge-capacity}} guests across 6 rooms. The lodge has a fully equipped communal kitchen, dining area, lounge, drying room, and ski storage. Bedding is provided. The lodge is accessible by 2WD vehicle in summer and requires 4WD or chains in winter snow conditions.</p></details><details><summary>What should I bring?</summary><p>Bring your own sleeping bag or hire one. The lodge provides pillows and mattresses. Pack warm clothing, appropriate footwear for the season, and any personal toiletries. If skiing, you can store your gear in the drying room. Check the weather forecast before your trip &mdash; conditions on the mountain can change quickly.</p></details><details><summary>How do chore rosters work?</summary><p>Every guest staying at the lodge is assigned a chore to help keep it clean and tidy. The hut leader for the night assigns chores (such as cleaning the kitchen, vacuuming, or tidying bathrooms) based on who is staying. You'll receive an email with your assigned chore. Chores are shared fairly and take around 15 to 30 minutes. It's how we keep lodge fees affordable for everyone.</p></details></div>
<div><h2>Privacy &amp; Account</h2><details><summary>What personal data does the club hold about me?</summary><p>The club holds your name, email address, phone number, date of birth, booking history, payment records, and chore assignments. This information is used to manage bookings and club membership. See our Privacy Policy for full details on how your data is collected, stored, and used.</p></details><details><summary>How do I update my personal details?</summary><p>Log in and go to your Profile page to update your name, phone number, and date of birth. To change your email address, use the "Change Email" section on your profile &mdash; you'll need to verify the new address. To change your password, use the "Change Password" option.</p></details></div>
<div class="website-legal-callout"><h2>Still have a question?</h2><p>Can't find what you're looking for? Get in touch and we'll help.</p><p><a href="/contact">Contact Us</a></p></div>
</div>$cms$,
    "updatedAt" = NOW()
WHERE "slug" = 'faq'
  AND "contentHtml" = $previous$<div class="website-legal-copy">
<div><h2>Booking &amp; Stays</h2><details><summary>How do I book a stay at the lodge?</summary><p>Members can book directly through this website. Log in, click "Book a Stay", select your dates and add your guests. The calendar shows available beds for each night. You'll need a current membership subscription to book at member rates.</p></details><details><summary>What is the cancellation policy?</summary><p>Refunds are tiered based on how much notice you give. Generally, cancellations 14 or more days before your stay receive a full refund. Between 7 and 14 days you receive a partial refund, and cancellations with less than 7 days' notice receive no refund. The exact tiers are set by the committee and shown on the Club Rules page. Always cancel as early as possible if your plans change.</p></details><details><summary>What are the nightly rates?</summary><p>Rates vary by season (Winter and Summer) and by age group (Adult, Youth, Child). Members pay a significantly lower rate than non-member guests. Current rates are shown on the Join page. Non-member guests must be accompanied by a financial member.</p></details><details><summary>Can I stay at the lodge as a non-member?</summary><p>Yes, but you must be invited as a guest by a current financial member, who must also be staying at the lodge during your visit. Non-member bookings are subject to a 7-day priority hold: if a member-only booking needs the beds within 7 days of your check-in date, your booking may be bumped. You'll receive immediate notification and a full refund if this happens.</p></details><details><summary>How does the non-member priority (bumping) system work?</summary><p>The lodge gives priority to member bookings. When you book as a guest more than 7 days in advance, your booking is held as "Pending" until 7 days before check-in. If a member needs those beds and the lodge is at capacity, the most recently made non-member bookings are bumped first to free up space. You'll be notified immediately by email and receive a full refund. This system ensures members always have access to the lodge they help maintain.</p></details><details><summary>Can I change my booking dates?</summary><p>Yes, members can change their booking dates from the booking detail page, subject to availability. A change fee may apply if you're modifying a booking within the late-notice period. The system will show you the fee before you confirm the change.</p></details></div>
<div><h2>Membership</h2><details><summary>How do I become a member?</summary><p>Membership is by nomination. You need to be nominated by two existing financial members. Start by visiting the lodge as someone's guest, get to know some members, and ask if they'd be willing to nominate you. See the Join page for the full process.</p></details><details><summary>What does membership cost?</summary><p>There is a one-off entrance fee for new members, plus an annual subscription. Subscriptions run April to March and are invoiced through Xero. Family memberships cover all household members at a reduced combined rate. Contact the Treasurer for current fee amounts.</p></details><details><summary>When does the membership year run?</summary><p>The membership year runs from 1 April to 31 March. Annual subscriptions are due at the start of each year. Members with unpaid subscriptions lose access to member booking rates until their subscription is paid.</p></details><details><summary>How do I reset my password?</summary><p>Click "Forgot password?" on the login page and enter your email address. You'll receive a password reset link valid for one hour. If you don't receive the email, check your spam folder or contact the Booking Officer.</p></details></div>
<div><h2>The Lodge</h2><details><summary>What facilities does the lodge have?</summary><p>Waldvogel Lodge at Iwikau Village, Mt Ruapehu sleeps up to {{lodge-capacity}} guests across 6 rooms. The lodge has a fully equipped communal kitchen, dining area, lounge, drying room, and ski storage. Bedding is provided. The lodge is accessible by 2WD vehicle in summer and requires 4WD or chains in winter snow conditions.</p></details><details><summary>What should I bring?</summary><p>Bring your own sleeping bag or hire one. The lodge provides pillows and mattresses. Pack warm clothing, appropriate footwear for the season, and any personal toiletries. If skiing, you can store your gear in the drying room. Check the weather forecast before your trip &mdash; conditions on the mountain can change quickly.</p></details><details><summary>How do chore rosters work?</summary><p>Every guest staying at the lodge is assigned a chore to help keep it clean and tidy. The hut leader for the night assigns chores (such as cleaning the kitchen, vacuuming, or tidying bathrooms) based on who is staying. You'll receive an email with your assigned chore. Chores are shared fairly and take around 15 to 30 minutes. It's how we keep lodge fees affordable for everyone.</p></details></div>
<div><h2>Privacy &amp; Account</h2><details><summary>What personal data does the club hold about me?</summary><p>The club holds your name, email address, phone number, date of birth, booking history, payment records, and chore assignments. This information is used to manage bookings and club membership. See our Privacy Policy for full details on how your data is collected, stored, and used.</p></details><details><summary>How do I update my personal details?</summary><p>Log in and go to your Profile page to update your name, phone number, and date of birth. To change your email address, use the "Change Email" section on your profile &mdash; you'll need to verify the new address. To change your password, use the "Change Password" option.</p></details></div>
<div class="website-legal-callout"><h2>Still have a question?</h2><p>Can't find what you're looking for? Get in touch and we'll help.</p><p><a href="/contact">Contact Us</a></p></div>
</div>$previous$;
