ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "lifeMemberDate" TIMESTAMP(3);
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "committeeRole" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "associateMember" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "comments" TEXT;
