-- Issue #992: the starter "/faq" PageContent row backfilled by
-- 20260702090000_backfill_policy_page_content rendered each question as a
-- flat <h3>/<p> pair, losing the collapsible accordion of the pre-CMS FAQ
-- page. Rewrap every question/answer into a native <details>/<summary>
-- accordion item, collapsed by default like the pre-CMS page. The question
-- and answer text is unchanged.
--
-- The WHERE clause guards on "contentHtml" still holding the exact starter
-- value written by the backfill, so deployments where an admin has already
-- edited the FAQ page are left untouched.
--
-- Keep these values in sync with the "faq" entry in
-- prisma/starter-page-content.ts (enforced by
-- src/lib/__tests__/page-content-starter-backfill.test.ts).
UPDATE "PageContent"
SET
  "contentHtml" = $faq_new$<div class="website-legal-copy">
<div><h2>Booking &amp; Stays</h2><details><summary>How do I book a stay at the lodge?</summary><p>Members can book directly through this website. Log in, click "Book a Stay", select your dates and add your guests. The calendar shows available beds for each night. You'll need a current membership subscription to book at member rates.</p></details><details><summary>What is the cancellation policy?</summary><p>Refunds are tiered based on how much notice you give. Generally, cancellations 14 or more days before your stay receive a full refund. Between 7 and 14 days you receive a partial refund, and cancellations with less than 7 days' notice receive no refund. The exact tiers are set by the committee and shown on the Club Rules page. Always cancel as early as possible if your plans change.</p></details><details><summary>What are the nightly rates?</summary><p>Rates vary by season (Winter and Summer) and by age group (Adult, Youth, Child). Members pay a significantly lower rate than non-member guests. Current rates are shown on the Join page. Non-member guests must be accompanied by a financial member.</p></details><details><summary>Can I stay at the lodge as a non-member?</summary><p>Yes, but you must be invited as a guest by a current financial member, who must also be staying at the lodge during your visit. Non-member bookings are subject to a 7-day priority hold: if a member-only booking needs the beds within 7 days of your check-in date, your booking may be bumped. You'll receive immediate notification and a full refund if this happens.</p></details><details><summary>How does the non-member priority (bumping) system work?</summary><p>The lodge gives priority to member bookings. When you book as a guest more than 7 days in advance, your booking is held as "Pending" until 7 days before check-in. If a member needs those beds and the lodge is at capacity, the most recently made non-member bookings are bumped first to free up space. You'll be notified immediately by email and receive a full refund. This system ensures members always have access to the lodge they help maintain.</p></details><details><summary>Can I change my booking dates?</summary><p>Yes, members can change their booking dates from the booking detail page, subject to availability. A change fee may apply if you're modifying a booking within the late-notice period. The system will show you the fee before you confirm the change.</p></details></div>
<div><h2>Membership</h2><details><summary>How do I become a member?</summary><p>Membership is by nomination. You need to be nominated by two existing financial members. Start by visiting the lodge as someone's guest, get to know some members, and ask if they'd be willing to nominate you. See the Join page for the full process.</p></details><details><summary>What does membership cost?</summary><p>There is a one-off entrance fee for new members, plus an annual subscription. Subscriptions run April to March and are invoiced through Xero. Family memberships cover all household members at a reduced combined rate. Contact the Treasurer for current fee amounts.</p></details><details><summary>When does the membership year run?</summary><p>The membership year runs from 1 April to 31 March. Annual subscriptions are due at the start of each year. Members with unpaid subscriptions lose access to member booking rates until their subscription is paid.</p></details><details><summary>How do I reset my password?</summary><p>Click "Forgot password?" on the login page and enter your email address. You'll receive a password reset link valid for one hour. If you don't receive the email, check your spam folder or contact the Booking Officer.</p></details></div>
<div><h2>The Lodge</h2><details><summary>What facilities does the lodge have?</summary><p>Waldvogel Lodge at Iwikau Village, Mt Ruapehu sleeps up to {{lodge-capacity}} guests across 6 rooms. The lodge has a fully equipped communal kitchen, dining area, lounge, drying room, and ski storage. Bedding is provided. The lodge is accessible by 2WD vehicle in summer and requires 4WD or chains in winter snow conditions.</p></details><details><summary>What should I bring?</summary><p>Bring your own sleeping bag or hire one. The lodge provides pillows and mattresses. Pack warm clothing, appropriate footwear for the season, and any personal toiletries. If skiing, you can store your gear in the drying room. Check the weather forecast before your trip &mdash; conditions on the mountain can change quickly.</p></details><details><summary>How do chore rosters work?</summary><p>Every guest staying at the lodge is assigned a chore to help keep it clean and tidy. The hut leader for the night assigns chores (such as cleaning the kitchen, vacuuming, or tidying bathrooms) based on who is staying. You'll receive an email with your assigned chore. Chores are shared fairly and take around 15 to 30 minutes. It's how we keep lodge fees affordable for everyone.</p></details></div>
<div><h2>Privacy &amp; Account</h2><details><summary>What personal data does the club hold about me?</summary><p>The club holds your name, email address, phone number, date of birth, booking history, payment records, and chore assignments. This information is used to manage bookings and club membership. See our Privacy Policy for full details on how your data is collected, stored, and used.</p></details><details><summary>How do I update my personal details?</summary><p>Log in and go to your Profile page to update your name, phone number, and date of birth. To change your email address, use the "Change Email" section on your profile &mdash; you'll need to verify the new address. To change your password, use the "Change Password" option.</p></details></div>
<div class="website-legal-callout"><h2>Still have a question?</h2><p>Can't find what you're looking for? Get in touch and we'll help.</p><p><a href="/contact">Contact Us</a></p></div>
</div>$faq_new$,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE
  "slug" = 'faq'
  AND "contentHtml" = $faq_old$<div class="website-legal-copy">
<div><h2>Booking &amp; Stays</h2><h3>How do I book a stay at the lodge?</h3><p>Members can book directly through this website. Log in, click "Book a Stay", select your dates and add your guests. The calendar shows available beds for each night. You'll need a current membership subscription to book at member rates.</p><h3>What is the cancellation policy?</h3><p>Refunds are tiered based on how much notice you give. Generally, cancellations 14 or more days before your stay receive a full refund. Between 7 and 14 days you receive a partial refund, and cancellations with less than 7 days' notice receive no refund. The exact tiers are set by the committee and shown on the Club Rules page. Always cancel as early as possible if your plans change.</p><h3>What are the nightly rates?</h3><p>Rates vary by season (Winter and Summer) and by age group (Adult, Youth, Child). Members pay a significantly lower rate than non-member guests. Current rates are shown on the Join page. Non-member guests must be accompanied by a financial member.</p><h3>Can I stay at the lodge as a non-member?</h3><p>Yes, but you must be invited as a guest by a current financial member, who must also be staying at the lodge during your visit. Non-member bookings are subject to a 7-day priority hold: if a member-only booking needs the beds within 7 days of your check-in date, your booking may be bumped. You'll receive immediate notification and a full refund if this happens.</p><h3>How does the non-member priority (bumping) system work?</h3><p>The lodge gives priority to member bookings. When you book as a guest more than 7 days in advance, your booking is held as "Pending" until 7 days before check-in. If a member needs those beds and the lodge is at capacity, the most recently made non-member bookings are bumped first to free up space. You'll be notified immediately by email and receive a full refund. This system ensures members always have access to the lodge they help maintain.</p><h3>Can I change my booking dates?</h3><p>Yes, members can change their booking dates from the booking detail page, subject to availability. A change fee may apply if you're modifying a booking within the late-notice period. The system will show you the fee before you confirm the change.</p></div>
<div><h2>Membership</h2><h3>How do I become a member?</h3><p>Membership is by nomination. You need to be nominated by two existing financial members. Start by visiting the lodge as someone's guest, get to know some members, and ask if they'd be willing to nominate you. See the Join page for the full process.</p><h3>What does membership cost?</h3><p>There is a one-off entrance fee for new members, plus an annual subscription. Subscriptions run April to March and are invoiced through Xero. Family memberships cover all household members at a reduced combined rate. Contact the Treasurer for current fee amounts.</p><h3>When does the membership year run?</h3><p>The membership year runs from 1 April to 31 March. Annual subscriptions are due at the start of each year. Members with unpaid subscriptions lose access to member booking rates until their subscription is paid.</p><h3>How do I reset my password?</h3><p>Click "Forgot password?" on the login page and enter your email address. You'll receive a password reset link valid for one hour. If you don't receive the email, check your spam folder or contact the Booking Officer.</p></div>
<div><h2>The Lodge</h2><h3>What facilities does the lodge have?</h3><p>Waldvogel Lodge at Iwikau Village, Mt Ruapehu sleeps up to {{lodge-capacity}} guests across 6 rooms. The lodge has a fully equipped communal kitchen, dining area, lounge, drying room, and ski storage. Bedding is provided. The lodge is accessible by 2WD vehicle in summer and requires 4WD or chains in winter snow conditions.</p><h3>What should I bring?</h3><p>Bring your own sleeping bag or hire one. The lodge provides pillows and mattresses. Pack warm clothing, appropriate footwear for the season, and any personal toiletries. If skiing, you can store your gear in the drying room. Check the weather forecast before your trip &mdash; conditions on the mountain can change quickly.</p><h3>How do chore rosters work?</h3><p>Every guest staying at the lodge is assigned a chore to help keep it clean and tidy. The hut leader for the night assigns chores (such as cleaning the kitchen, vacuuming, or tidying bathrooms) based on who is staying. You'll receive an email with your assigned chore. Chores are shared fairly and take around 15 to 30 minutes. It's how we keep lodge fees affordable for everyone.</p></div>
<div><h2>Privacy &amp; Account</h2><h3>What personal data does the club hold about me?</h3><p>The club holds your name, email address, phone number, date of birth, booking history, payment records, and chore assignments. This information is used to manage bookings and club membership. See our Privacy Policy for full details on how your data is collected, stored, and used.</p><h3>How do I update my personal details?</h3><p>Log in and go to your Profile page to update your name, phone number, and date of birth. To change your email address, use the "Change Email" section on your profile &mdash; you'll need to verify the new address. To change your password, use the "Change Password" option.</p></div>
<div class="website-legal-callout"><h2>Still have a question?</h2><p>Can't find what you're looking for? Get in touch and we'll help.</p><p><a href="/contact">Contact Us</a></p></div>
</div>$faq_old$;
