-- Issue #997: named admin access bundles backed by MemberAccessRole.
ALTER TYPE "AccessRole" ADD VALUE IF NOT EXISTS 'ADMIN_READONLY';
ALTER TYPE "AccessRole" ADD VALUE IF NOT EXISTS 'ADMIN_BOOKINGS';
ALTER TYPE "AccessRole" ADD VALUE IF NOT EXISTS 'ADMIN_MEMBERSHIP';
ALTER TYPE "AccessRole" ADD VALUE IF NOT EXISTS 'ADMIN_CONTENT';
